[2025-07-28T13:05:55.222+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T13:05:55.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburant_etl_dag.transform_data manual__2025-07-28T13:00:52.188198+00:00 [queued]>
[2025-07-28T13:05:55.248+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburant_etl_dag.transform_data manual__2025-07-28T13:00:52.188198+00:00 [queued]>
[2025-07-28T13:05:55.248+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-28T13:05:55.258+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-07-28 13:00:52.188198+00:00
[2025-07-28T13:05:55.265+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=257) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T13:05:55.266+0000] {standard_task_runner.py:63} INFO - Started process 259 to run task
[2025-07-28T13:05:55.265+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'carburant_etl_dag', 'transform_data', 'manual__2025-07-28T13:00:52.188198+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_carburant.py', '--cfg-path', '/tmp/tmp5bhyrt_f']
[2025-07-28T13:05:55.267+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask transform_data
[2025-07-28T13:05:55.278+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-28T13:05:55.305+0000] {task_command.py:426} INFO - Running <TaskInstance: carburant_etl_dag.transform_data manual__2025-07-28T13:00:52.188198+00:00 [running]> on host 90fdb4201ee5
[2025-07-28T13:05:55.369+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='carburant_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T13:00:52.188198+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T13:00:52.188198+00:00'
[2025-07-28T13:05:55.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T13:05:55.377+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T13:05:55.499+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/transform/transform_data.py", line 9, in transform_xml
    tree = ET.parse(xml_path)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 569, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
[2025-07-28T13:05:55.507+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=carburant_etl_dag, task_id=transform_data, run_id=manual__2025-07-28T13:00:52.188198+00:00, execution_date=20250728T130052, start_date=20250728T130555, end_date=20250728T130555
[2025-07-28T13:05:55.514+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task transform_data (not well-formed (invalid token): line 1, column 2; 259)
[2025-07-28T13:05:55.531+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T13:05:55.549+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T13:05:55.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
