[2025-07-28T13:23:52.549+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T13:23:52.568+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburant_etl_dag.load_data scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T13:23:52.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburant_etl_dag.load_data scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T13:23:52.576+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-28T13:23:52.584+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-07-27 00:00:00+00:00
[2025-07-28T13:23:52.589+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=194) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T13:23:52.589+0000] {standard_task_runner.py:63} INFO - Started process 199 to run task
[2025-07-28T13:23:52.589+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'carburant_etl_dag', 'load_data', 'scheduled__2025-07-27T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_carburant.py', '--cfg-path', '/tmp/tmp268ugqll']
[2025-07-28T13:23:52.591+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask load_data
[2025-07-28T13:23:52.599+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-28T13:23:52.624+0000] {task_command.py:426} INFO - Running <TaskInstance: carburant_etl_dag.load_data scheduled__2025-07-27T00:00:00+00:00 [running]> on host 23a33819e131
[2025-07-28T13:23:52.679+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='carburant_etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-27T00:00:00+00:00'
[2025-07-28T13:23:52.680+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T13:23:57.296+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T13:23:57.298+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/load/load_to_postgres.py", line 11, in load_to_db
    cursor.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(prix_carburants, 2200) already exists.

[2025-07-28T13:23:57.310+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=carburant_etl_dag, task_id=load_data, run_id=scheduled__2025-07-27T00:00:00+00:00, execution_date=20250727T000000, start_date=20250728T132352, end_date=20250728T132357
[2025-07-28T13:23:57.318+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task load_data (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(prix_carburants, 2200) already exists.
; 199)
[2025-07-28T13:23:57.368+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T13:23:57.385+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T13:23:57.387+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
