[2025-07-28T13:05:49.573+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T13:05:49.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburant_etl_dag.transform_data scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T13:05:49.597+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburant_etl_dag.transform_data scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T13:05:49.597+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-28T13:05:49.604+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-07-27 00:00:00+00:00
[2025-07-28T13:05:49.609+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T13:05:49.610+0000] {standard_task_runner.py:63} INFO - Started process 256 to run task
[2025-07-28T13:05:49.609+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'carburant_etl_dag', 'transform_data', 'scheduled__2025-07-27T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_carburant.py', '--cfg-path', '/tmp/tmpan2ieege']
[2025-07-28T13:05:49.611+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask transform_data
[2025-07-28T13:05:49.631+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-28T13:05:49.653+0000] {task_command.py:426} INFO - Running <TaskInstance: carburant_etl_dag.transform_data scheduled__2025-07-27T00:00:00+00:00 [running]> on host 90fdb4201ee5
[2025-07-28T13:05:49.699+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='carburant_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-27T00:00:00+00:00'
[2025-07-28T13:05:49.700+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T13:05:49.708+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T13:05:49.923+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/transform/transform_data.py", line 9, in transform_xml
    tree = ET.parse(xml_path)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 569, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
[2025-07-28T13:05:49.932+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=carburant_etl_dag, task_id=transform_data, run_id=scheduled__2025-07-27T00:00:00+00:00, execution_date=20250727T000000, start_date=20250728T130549, end_date=20250728T130549
[2025-07-28T13:05:49.937+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task transform_data (not well-formed (invalid token): line 1, column 2; 256)
[2025-07-28T13:05:49.963+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T13:05:49.977+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T13:05:49.979+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-28T13:18:57.864+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T13:18:57.889+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburant_etl_dag.transform_data scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T13:18:57.893+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburant_etl_dag.transform_data scheduled__2025-07-27T00:00:00+00:00 [queued]>
[2025-07-28T13:18:57.893+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-28T13:18:57.900+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-07-27 00:00:00+00:00
[2025-07-28T13:18:57.905+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=249) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T13:18:57.906+0000] {standard_task_runner.py:63} INFO - Started process 252 to run task
[2025-07-28T13:18:57.905+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'carburant_etl_dag', 'transform_data', 'scheduled__2025-07-27T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_carburant.py', '--cfg-path', '/tmp/tmpu6w01tvw']
[2025-07-28T13:18:57.907+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask transform_data
[2025-07-28T13:18:57.920+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-28T13:18:57.982+0000] {task_command.py:426} INFO - Running <TaskInstance: carburant_etl_dag.transform_data scheduled__2025-07-27T00:00:00+00:00 [running]> on host 695a2fdba44c
[2025-07-28T13:18:58.036+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='carburant_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-27T00:00:00+00:00'
[2025-07-28T13:18:58.036+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T13:18:58.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T13:18:58.383+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/transform/transform_data.py", line 9, in transform_xml
    tree = ET.parse(xml_path)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 569, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
[2025-07-28T13:18:58.403+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=carburant_etl_dag, task_id=transform_data, run_id=scheduled__2025-07-27T00:00:00+00:00, execution_date=20250727T000000, start_date=20250728T131857, end_date=20250728T131858
[2025-07-28T13:18:58.410+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task transform_data (not well-formed (invalid token): line 1, column 2; 252)
[2025-07-28T13:18:58.417+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T13:18:58.440+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T13:18:58.444+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
